"""initial_schema

Revision ID: ca391f8bf2e6
Revises: 
Create Date: 2026-06-27 06:58:17.383068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca391f8bf2e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_revoked_tokens_expires_at'), 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index('ix_revoked_tokens_hash', 'revoked_tokens', ['token_hash'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_ts', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_user_ts', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=False),
    sa.Column('to_user_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_msg_thread', 'messages', ['from_user_id', 'to_user_id', 'sent_at'], unique=False)
    op.create_index('ix_msg_to_unread', 'messages', ['to_user_id', 'read_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_prt_hash', 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('value_sec', sa.Float(), nullable=False),
    sa.Column('value_disp', sa.String(), nullable=True),
    sa.Column('achieved_at', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('garmin_activity_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pr_user_event', 'personal_records', ['user_id', 'event'], unique=False)
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('assigned_workouts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index('ix_aw_athlete_date', 'assigned_workouts', ['athlete_id', 'date_iso'], unique=False)
    op.create_index('ix_aw_date', 'assigned_workouts', ['date_iso'], unique=False)
    op.create_unique_constraint('uq_aw_template_athlete_date', 'assigned_workouts', ['template_id', 'athlete_id', 'date_iso'])
    op.create_index(op.f('ix_blood_lab_exams_user_id'), 'blood_lab_exams', ['user_id'], unique=False)
    op.add_column('group_members', sa.Column('athlete_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_group_members_athlete_id'), 'group_members', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'users', ['athlete_id'], ['id'])
    op.drop_column('group_members', 'user_id')
    op.create_index(op.f('ix_nutrition_plans_user_id'), 'nutrition_plans', ['user_id'], unique=False)
    op.alter_column('users', 'garmin_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'garmin_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'race_goal_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'race_goal_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'race_goal_dist',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'weight_kg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'vo2max',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'css',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'run_pace',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'token_gen',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'totp_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('wellness_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_wellness_logs_user_id'), 'wellness_logs', ['user_id'], unique=False)
    op.create_index('ix_wellness_user_date', 'wellness_logs', ['user_id', 'date_iso'], unique=False)
    op.add_column('workout_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_workout_logs_assignment_id'), 'workout_logs', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.alter_column('workout_templates', 'tipo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_templates', 'tipo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_assignment_id'), table_name='workout_logs')
    op.drop_column('workout_logs', 'deleted_at')
    op.drop_index('ix_wellness_user_date', table_name='wellness_logs')
    op.drop_index(op.f('ix_wellness_logs_user_id'), table_name='wellness_logs')
    op.drop_column('wellness_logs', 'deleted_at')
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'totp_secret',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'token_gen',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'run_pace',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'css',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'vo2max',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('users', 'weight_kg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('users', 'race_goal_dist',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'race_goal_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'race_goal_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'garmin_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'garmin_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_nutrition_plans_user_id'), table_name='nutrition_plans')
    op.add_column('group_members', sa.Column('user_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_athlete_id'), table_name='group_members')
    op.drop_column('group_members', 'athlete_id')
    op.drop_index(op.f('ix_blood_lab_exams_user_id'), table_name='blood_lab_exams')
    op.drop_constraint('uq_aw_template_athlete_date', 'assigned_workouts', type_='unique')
    op.drop_index('ix_aw_date', table_name='assigned_workouts')
    op.drop_index('ix_aw_athlete_date', table_name='assigned_workouts')
    op.drop_column('assigned_workouts', 'deleted_at')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index('ix_pr_user_event', table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index('ix_prt_hash', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_msg_to_unread', table_name='messages')
    op.drop_index('ix_msg_thread', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_audit_user_ts', table_name='audit_logs')
    op.drop_index('ix_audit_action_ts', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_revoked_tokens_hash', table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_expires_at'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
