"""
Generates data/workout_lookup.js from the raw Garmin JSON cache.
Includes workoutId + hasIntensityIntervals per activity_id.
Run after any Garmin sync.
"""
import sys, json, os, glob
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

BASE = 'C:/Users/rafae/projects/LabX/'

# Find the most recent activities cache file
cache_dir = BASE + 'data/cache/'
candidates = sorted(glob.glob(cache_dir + 'activities_*.json'), reverse=True)
if not candidates:
    print('ERROR: no activities cache found')
    sys.exit(1)

cache_file = candidates[0]
print(f'Reading: {cache_file}')

with open(cache_file, encoding='utf-8', errors='replace') as f:
    data = json.load(f)

acts = data if isinstance(data, list) else data.get('activities', [])
print(f'Total activities: {len(acts)}')

lookup = {}
for a in acts:
    aid = a.get('activityId') or a.get('activity_id')
    if not aid:
        continue
    workout_id  = a.get('workoutId') or 0
    has_intv    = bool(a.get('hasIntensityIntervals'))
    course_id   = a.get('courseId') or 0
    if workout_id or has_intv or course_id:
        lookup[str(int(aid))] = {
            'w': int(workout_id) if workout_id else 0,
            'i': 1 if has_intv else 0,
            'c': int(course_id) if course_id else 0,
        }

print(f'Activities with planning signals: {len(lookup)}')

# Write JS file
out_path = BASE + 'data/workout_lookup.js'
lines = ['/* Auto-generated by build_workout_lookup.py — DO NOT EDIT */\n']
lines.append('var KL_WORKOUT_LOOKUP = {\n')
entries = []
for aid, v in sorted(lookup.items(), key=lambda x: int(x[0])):
    entries.append(f'  "{aid}": {json.dumps(v)}')
lines.append(',\n'.join(entries))
lines.append('\n};\n')

with open(out_path, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print(f'Written: {out_path}')
print(f'  workoutId set:       {sum(1 for v in lookup.values() if v["w"])}')
print(f'  has_intervals:       {sum(1 for v in lookup.values() if v["i"])}')
print(f'  courseId set:        {sum(1 for v in lookup.values() if v["c"])}')
