[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base                     = "light"
primaryColor             = "#3B82F6"
backgroundColor          = "#F1F5F9"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#0F172A"
font                     = "sans serif"
